### ISSUE TITLE
EndeavourOS Installer

### ISSUE THREAD

**Issue by onkoe** [EmeraldSnorlax/manjarno#11]
Hi, 
It may be worth reconsidering the short summary about EndeavourOS as an Arch alternative. Compared to archinstall, Calamares - which is Endeavour's installer - offers many more options. These include package selection, handcrafted package groups, automatic partitioning, hardware detection, and timezone mapping. These make the install process quite a bit easier for newer Arch users. 

In my view, Calamares is a much more moderate experience that more users can understand. A good way to put it is in terms of the Windows power-user. Most of them couldn't use a CLI installer to save their lives, but they can usually make their way through a GUI installer like Calamares... or Windows 10. For this reason, I believe a slight revision of the Endeavour section may better reach the goals of the project. It also helps to meet Manjaro's original goal of making Arch easier. Please let me know if this is agreeable or not - I may look like a bit of a shill. Thanks!

**Comment by EmeraldSnorlax** [comment]
I've made some changes in https://github.com/EmeraldSnorlax/manjarno/commit/522497b6960d797ebd25e171e199ef9d9697503d; does that seem like what you were looking for? If not, feel free to make a PR. If it is, you can close this issue

**Comment by EmeraldSnorlax** [comment]
(i am great at catching typos)

**Comment by onkoe** [comment]
I've made a few changes to the text to seem more stylistically in line with previous paragraphs. I'm not entirely certain how to implement it since I generally don't touch web stuff, but if you like it, please feel free to use it. Otherwise, your changes are great. Thanks for your consideration and time! :) 

EndeavourOS seems to be what Manjaro is going for - just rightly done as far as I can tell. That said, using an Arch derivative is still a bit questionable in my view. The main excuse for doing so (lack of an automated installer) doesn't apply anymore as Arch ships with `archinstall`. However, EndeavourOS has a GUI installer, which should be much more approachable, and offers many more configurations to choose from out of the box than `archinstall`.
