### ISSUE TITLE
Incorrect date: Month is off by one

### ISSUE THREAD

**Issue by garrett** [EmeraldSnorlax/manjarno#16]
Thanks for raising awareness of Manjaro's flub-ups! One is a mistake, four times is chronic. :disappointed: People should be able to trust their distribution, whichever one they use — so thanks for pointing this out.

---

The certificate expired yesterday... while the counting timer shows the right information, the date is off by a month. Most likely: _Thanks, JavaScript!_

Screenshot:

![2022-08-18-092147_002](https://user-images.githubusercontent.com/10246/185336198-e0f9b42f-d3b4-46b2-bb9a-7cbb195e6a39.png)

However: Today's date is 2022-**08**-18.

It's probably related to [Date.getMonth](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth) returning current month as a number between 0 and 11, instead of 1 - 12.

**Comment by EmeraldSnorlax** [comment]
ah, good catch!
