### ISSUE TITLE
Some News about PINE64 and Manjaro

### ISSUE THREAD

**Issue by JiaZhangJiaZhangJiaZhangJiaZhang** [EmeraldSnorlax/manjarno#23]
I think this article doesn't have anything to do with manjarno web page, but just for good read: https://blog.brixit.nl/why-i-left-pine64/

Partial quote:
```
In some cases the Manjaro involvement actually causes extra workload for the developers by shipping known broken versions of software and pointing to the developers for support. Which is why https://dont-ship.it/ was started.
```

**Comment by EmeraldSnorlax** [comment]
thanks, interesting read but i personally dont think it belongs on this page right now
im open to further discussion on this (now, or in the future) though

**Comment by BillFleming** [comment]
You should create a separate page to detail this (growing) side of the manjaro problem.

**Comment by EmeraldSnorlax** [comment]
> You should create a separate page to detail this (growing) side of the manjaro problem.

hi, i don't want to maintain this anymore
see #39
