### ISSUE TITLE
Shipping custom (broken) Firefox theme on Manjaro GNOME

### ISSUE THREAD

**Issue by TheEvilSkeleton** [EmeraldSnorlax/manjarno#26]
This might look minor at a first glance, but it is genuinely a problem, as it is a massive accessibility regression.

References:
- https://floss.social/@rafaelmardojai/109532714277650579
- https://www.reddit.com/r/firefox/comments/zn589n/firefox_updates_it_self_and_now_my_tab_bar_looks

**Comment by theAkito** [comment]
When a major issue seems like a minor one to a majority of users, it makes the issue even worse.

**Comment by EricZhang456** [comment]
MANJARNOOOOOOOOOOO

**Comment by EricZhang456** [comment]
MANJARNOOOOOOOOOOO

**Comment by TheEvilSkeleton** [comment]
This was addressed
