### ISSUE TITLE
Manjaros "stance" on "patent encumbered" codecs

### ISSUE THREAD

**Issue by Mr-nUUb** [EmeraldSnorlax/manjarno#29]
- Exact date this sh*tshow began: [2022-12-06](https://forum.manjaro.org/t/stable-update-2022-12-06-kernels-mesa-plasma-cinnamon-nvidia-libreoffice-pipewire-virtualbox/128453)
- [disabling](https://gitlab.manjaro.org/packages/extra/mesa/-/commit/e4fbdd707b144863a49e29d7940d735beeb2cba1) of "patent encumbered" codecs
- [reenabling](https://gitlab.manjaro.org/packages/extra/mesa/-/commit/ee41ff6c08b375cb3eb60bb0b7f05cf9a7fa1a68) of aforementioned code
- [redisabling](https://gitlab.manjaro.org/packages/extra/mesa/-/commit/0d936924dd9b519868104fc82c6bb486092b9e72) of aforementioned code
- This [explanation](https://forum.manjaro.org/t/getting-hardware-accelerated-decode-in-various-software-in-manjaro-after-recent-changes-in-mesa/128909/10) is all about copyright, which is [not the same thing](https://copyrightalliance.org/faqs/difference-copyright-patent-trademark/) and has nothing to do with this stupidity.
- Manjaro team member recommending [migration to Arch](https://forum.manjaro.org/t/upstream-mesa-removal-of-avc-hevc-vc-1-hardware-acceleration-amd-gpus/128385/78).
- They clearly don't know what they're doing.
- Even [Debian still ships them](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1016687#50).
- [Video by Brodie Robertson](https://youtu.be/Cw_sJz7li8E). TL;DR: if you don't know why you're doing something, stop doing it.

**Comment by EmeraldSnorlax** [comment]
i honestly don't know enough about this to comment. from what i've gathered, it just looks like they're trying to cover themselves legally? i remember a few other distros like fedora disabling hardware acceleration for these codecs, so what makes this different?

in my (subjective) opinion, this looks like an understandable legal change and i'm willing to give them the benefit of the doubt. still, i'm open to more discussion on this

**Comment by Mr-nUUb** [comment]
Manjaro GmbH is a company in Germany. They should seek legal advice first before screwing around like that. Furthermore, the [European Patent Convention states that software is not patentable](https://www.epo.org/law-practice/legal-texts/html/epc/2016/e/ar52.html).

The thing is: they actively advise against using 3rd party repos or installing the Arch packages. Before this change, they even used unmodified Arch packages for mesa, and now it's discouraged? C'mon. According to them, cloning the PKGBUILD or using mesa-git from AUR (and rebuilding on every single update) are the only solutions. Something like mesa-freeworld on RPMFusion? Nope, not with Manjaro!

I want to use all capabilities of my hardware. Manjaro simply prevents this and suggests impractical Ssolutions". As a EU citizen, I will just use a community driven distro and abandon Manjaro.

**Comment by FabioLolix** [comment]
>Manjaro GmbH is a company in Germany

Also is SUSE and is reported that they have disabled the video codecs 
* https://lwn.net/Articles/910978/
* https://build.opensuse.org/request/show/1006922
* https://build.opensuse.org/request/show/1006922#comment-1681415
* https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15258/diffs

> they even used unmodified Arch packages for mesa

Like 95% or more of Manjaro packages are imported from Arch, not a news

**Comment by Mr-nUUb** [comment]
> Like 95% or more of Manjaro packages are imported from Arch, not a news

Didn't get my point. Why is it now discouraged if previously it was fine? The only difference is the disabling of these codecs.

**Comment by FabioLolix** [comment]
> Why is it now discouraged if previously it was fine? The only difference is the disabling of these codecs.

Because before no one thought about it seems https://lwn.net/Articles/910978/

**Comment by Mr-nUUb** [comment]
> Because before no one thought about it seems https://lwn.net/Articles/910978/

How often are you going to post this article I've already read? I wasn't talking about this specific package. I was talking in general about unmodified Arch packages. Why is it discouraged? I also have to update Discord from Arch because Manjaro is just too slow to deliver an up2date version that actually starts and connects. Is this discouraged too? Manjaros Discord package is indeed unmodified. Am I breaking something by installing the Arch package?

**Comment by Mr-nUUb** [comment]
> By installing Discord no because is self-contained, for mesa you need to install the Arch package with the same timing they are updating mesa for avoiding versions mismatch

Still discouraged? https://github.com/Mr-nUUb/manjaro-mesa-freeworld/blob/main/mesa-freeworld.sh

**Comment by EmeraldSnorlax** [comment]
> Manjaro GmbH is a company in Germany. They should seek legal advice first before screwing around like that. Talking about copyright but meaning patents is a good indication they don't know anything about that and haven't consulted a lawyer. Furthermore, the [European Patent Convention states that software is not patentable](https://www.epo.org/law-practice/legal-texts/html/epc/2016/e/ar52.html).

being in a certain country does not make you immune to other countries' laws if you are operating in that country (see gdpr and american websites blocking european visitors)

> I want to use all capabilities of my hardware. Manjaro simply prevents this and suggests impractical "solutions". As a EU citizen, I will just use a community driven distro and abandon Manjaro.

then do so. i feel this is out of scope of this article

**Comment by Mr-nUUb** [comment]
What? Since when does eg. German law apply to France? Are they going to send the German Police to arrest me because I said something forbidden in Germany even though I'm in France?

This is about operating systems on personal Computers and not about web servers/services..

Whatever, I'll abandon this thread, too.

**Comment by EmeraldSnorlax** [comment]
> What? Since when does eg. German law apply to France? Are they going to send the German Police to arrest me because I said something forbidden in Germany even though I'm in France?

false equivalence. a better approximation would be if you went to germany and did something illegal in germany. it doesn't matter that you are from france, you did it in germany.

**Comment by Mr-nUUb** [comment]
Yeah whatever.

**Comment by not-ivy** [comment]
https://github.com/nikolas/github-drama

**Comment by theAkito** [comment]
Just here to point out how EmeraldSnorlax is talking based on facts as far as it is possible for him, while Mr-nUUb is providing all honour to his name by speaking out of pure feelings.



> being based in a certain country does not make you immune to other countries' laws if you are operating in that country (see gdpr and american websites blocking european visitors because they don't want to be compliant)



> false equivalence. a better approximation would be if you went to germany and did something illegal in germany but not france. it doesn't matter that you are from france, you did it in germany.

For example, this is absolutely true. If you provide services in that country, then you must be compliant with the laws in that area.
Same reason why Google & Facebook have to constantly pay millions of € penalties for their bullshit they fuck up in Europe.

**Comment by Mr-nUUb** [comment]
AFAIK in regards to h264/h265/VC1 the patent fee applies to the system as a whole. So the user should pay the fee or bear the consequences. After all, it's the users decision what OS or tools to use. Manjaro providing a download does NOT decode or encode any video material and should therefore not be held responsible. Over and out.

**Comment by FabioLolix** [comment]
Latest development https://forum.manjaro.org/t/behind-the-scene-manjaro-community-mesa-nonfree-codecs/135012

**Comment by EmeraldSnorlax** [comment]
> Latest development [forum.manjaro.org/t/behind-the-scene-manjaro-community-mesa-nonfree-codecs/135012](https://forum.manjaro.org/t/behind-the-scene-manjaro-community-mesa-nonfree-codecs/135012)

link is dead
