### ISSUE TITLE
WIP asahi stuff (again)

### ISSUE THREAD

**Issue by RiedleroD** [EmeraldSnorlax/manjarno#34]
https://social.treehouse.systems/@marcan/110049540523616625

the change was requested by the project lead from the manjaro-arm team, presumably to get the change downstream in their project so it's arguably manjaro fucking up again. It's up to you if that counts though.

**Comment by RiedleroD** [comment]
oh, I missed when the PR was opened. Maybe add it as a footnote to the existing paragraph on this?

**Comment by EmeraldSnorlax** [comment]
that's mildly amusing, but i don't think it's worth including. feel free to discuss further though

**Comment by EmeraldSnorlax** [comment]
yeah i read the pr, it just looks like the mistake of one manjaro dev (albeit the manjaro arm lead...) and then then alarm trusting the pr too without testing -- alarm would be at least as responsible for the patch too

i guess writing it out now, it could have a sentence or two
