### ISSUE TITLE
Rushing Asahi out the door - background story

### ISSUE THREAD

**Issue by philmmanjaro** [EmeraldSnorlax/manjarno#37]
The following text is found on your website:
> Rushing Asahi out the door
>
>In their attempt to get Asahi Linux out (and support Apple Silicon) as soon as possible, they ended pulling the latest PKGBUILD without talking to the devs. This has resulted in them shipping potentially broken kernels to end users.
>
>Still though, that’s besides the main problem. It was only about 3 days ago this video came out, in which a DE is working for the first time. Not only is it still in a state far from prime-time, but compounded with the tweet above they didn’t even bother trying to speak with the devs of the project about its current state.

First of all I'm not in the mood to rush out things. It took me some time and 3 image builds to get the OS working on my M1 Air. 

## How did it happend

Using the latest Version of the PKGBUILD is more or less common if you deal with Arch Linux based software. Also the released version of the image had a disclaimer:

> DISCLAIMER: THESE ARE EXPERIMENTAL IMAGES ON WHICH WE TEST ON HOW TO BUILD FOR APPLE SILICON. THESE IMAGES ARE BASED ON ASAHI 6.0 KERNEL SERIES. USE THIS AT YOUR OWN RISK!
>
>These are initial images for Apple Silicon devices starting
with the 2020 M1 MacBook Air.
>
>A huge thank you goes to the Asahi Linux project of which we use
their tools slightly modified to support Manjaro Linux ARM.
>
>All Apple M1 Macs are in scope, as well as future generations as
development time permits. The first target will be the 2020 M1 MacBook Air.

As soon as the Twitter post was out I reacted and pulled the images and installer from sourceforge. They are now stored at an unlisted storage server for internal usage after rebuilding the image with the packages available that time of **asahi** repo. Before I update [my PKGBUILDs](https://gitlab.manjaro.org/groups/manjaro-arm/packages/apple-silicon/-/activity) I check if those changes also match the [binary repos](https://cdn.asahilinux.org/aarch64/asahi/) of Asahi. Also the issue with the M1 Ultra was given by our first public release, but was never our target to begin with, as we only list devices we actually have tested on our end with Manjaro ARM.

Additionally Asahi upstream started a while ago to branch their git repos for [development](https://github.com/AsahiLinux/PKGBUILDs/commits/dev), similar to Arch. This helps distros to adopt much easier and follow on what might coming up next.

Sure establishing a connection with Asahi to begin with would have been better. The email I had sent to Marcan on the day I pulled the initial images and explained what had happened was never answered.

>On 02.10.22 21:13, Philip Müller wrote:
> Hello Hector,
> 
> seems the initial image release of Manjaro on Apple Silicon wasn't as 
> attended to be. There were some issues with it introduced by me on our end.
> 
> Kernel
> -------
> 
> I pulled all images which were public available. Based on the statistics 
> around 200 people seem to have downloaded them till the moment I deleted 
> them.
> 
> The first image had some issue with init and Calamares branding and was 
> therefore not bootable for a normal user. The second image fixed that 
> and booted fine on my M1 Air. So I decided to tweet about it. That might 
> have been to early, though.
> 
> Thx for pointing out that there are issues on the M1 Ultra on the 6.0 
> kernel series, which we can't test from our end. I pulled the kernel 
> from our repos and replaced it by the working 5.19 rev5 kernel.
> 
> I'll try to connect with you on when a kernel can be updated.
> 
> Internal Images
> ----------------
> 
> I moved the current internal images to our SCRUBBED FOR LEGAL REASONS, which doesn't 
> list the server folder structure. Here the links to important files:
> 
>SCRUBBED FOR LEGAL REASONS
> 
> I'll test the image from scratch again on my end. So far only I have an 
> Apple Silicon device within the Manjaro ARM project. Therefore I'll only 
> been able to test on the Air for now.
> 
> Is there an easy way to just flash the new images to the SSD or is the 
> remote installer approach the only way for now? Any documentation on 
> that would be highly appreciated.
> 
> Collaboration
> --------------
> 
> Our ARM developers what to connect with and collaborate to the Asahi 
> project. We will create PRs to related projects as soon as we think to 
> have an improvement for those. Here is one example I added on our end:
> 
> https://github.com/AsahiLinux/asahi-alarm-builder/pull/5
> 
> We respect the work from you and your whole team of Asahi project.
> 
> Hopefully we can press Stop, Pause, Rewind and start the Apple Silicon 
> support via Manjaro ARM on a better approach after more internal 
> discussions and testing between both FOSS projects.
> 
> On a personal note: I like to apologize for any issues caused by too 
> early tweeting from our end on the official Manjaro Twitter handle.

**Comment by marcan** [comment]
I love how you opened this issue right after [this](https://github.com/archlinuxarm/PKGBUILDs/pull/1946) was discovered and conveniently failed to mention it. If you want to collaborate... maybe start by not upstreaming broken things behind our back to our own upstream without as much as a mention?
