### ISSUE TITLE
project future

### ISSUE THREAD

**Issue by Animeshz** [EmeraldSnorlax/manjarno#39]

**Comment by Ecorous** [comment]
https://manjarno.pages.dev/ also works!

**Comment by ipaqmaster** [comment]
Jeez how did that happen... and this issue was made over a month ago but the domain is still dead? This repo references the domain.

This is on par with the distro this site was made for documenting. Is anything being done?

**Comment by MithicSpirit** [comment]
bump (still broken)

**Comment by EmeraldSnorlax** [comment]
hi, i'm gonna be honest here
i've taken a break from software for health reasons, and i'm doing better now, but i really do not want to keep maintaining this. you are more than welcome to fork this and continue it, and i think the cloudflare pages site should stay up indefinitely, but i think i want to move on from this.

**Comment by ipaqmaster** [comment]
No worries and understandable.

**Comment by theAkito** [comment]
@EmeraldSnorlax

All the best!

Maybe we find someone, willing to work on the next version of this project. 🙂

**Comment by EmeraldSnorlax** [comment]
*should anyone want the repo, and people can agree as a majority, i'm happy to transfer ownership. otherwise, feel free to fork onwards into your own things, but please be aware of the impact and culture that has spawned as a result
