### ISSUE TITLE
Manjaro accidentally removed packages like iputils, filesystem and etc from iso

### ISSUE THREAD

**Issue by Mar0xy** [EmeraldSnorlax/manjarno#7]
yesterday and today we had someone in our discord telling us ping was not found on manjaro about 4 hours later he linked to https://forum.manjaro.org/t/why-is-iputils-not-installed-by-default/98160
where it was found out that base packages got removed in one of the iso releases and had to be restored via this commit https://gitlab.manjaro.org/profiles-and-settings/iso-profiles/-/commit/07ffbb081ba4f38af5b73908d27afcd5c6906e9d

**Comment by EmeraldSnorlax** [comment]
eh, im not sure this is significant enough to warrant an entry
