### ISSUE TITLE
Add garuda to What should I use instead?

### ISSUE THREAD

**Issue by Thenujan-0** [EmeraldSnorlax/manjarno#8]
Garuda linux seems like a great distribution. why isnt it in the list?

**Comment by EmeraldSnorlax** [comment]
i felt like that niche (people who really dont want to use the cli, even with an automated installer) is already filled out quite well by endeavour. imo using arch derivatives in general is a little questionable now that the main excuse (lack of an automated installer) doesnt really apply. i'll add it as an alternative to endeavour in the site, though.

**Comment by Thenujan-0** [comment]
Endeavour os says it is A terminal-centric distro and you are saying it can be used by people who really dont want to use cli?
