### ISSUE TITLE
Manjaro DDoSing the AUR second time part is falsely described 

### ISSUE THREAD

**Issue by Thenujan-0** [EmeraldSnorlax/manjarno#9]
It wasn't because of any bugs in pamac it was because so many manjaro users were using pamac at the same time so they had to remove some features like sending requests on every key press . If you think sending requests on every key press is a bug then www.aur.archlinux.org has that bug.

**Comment by EmeraldSnorlax** [comment]
sending  requests on every single keypress still isn't a polite thing to do to a service that you don't own and don't even bother mirroring -- the kind of demand generated by pamac is in a different league from the search bar on the website imo. how would you word that section; im happy to consider alternatives

**Comment by JiaZhangJiaZhangJiaZhangJiaZhang** [comment]
Check this most recent AUR issue:

https://forum.manjaro.org/t/aur-please-restrain-yourself/103318
https://forum.endeavouros.com/t/is-aur-down-again/24287/3

AUR was down again recently. So this may be the 3rd time.

**Comment by Bluskript** [comment]
:woozy_face:

**Comment by yusdacra** [comment]
:woozy_face:

**Comment by spiralw** [comment]
:woozy_face:

**Comment by EmeraldSnorlax** [comment]
:woozy_face:

**Comment by repository** [comment]
🥴

**Comment by EmeraldSnorlax** [comment]
From reading these threads, it seems too me that Manjaro isn't provably the reason  for the AUR going down. However, the way that they've decided to treat their users about it is uh... contradictory, to say the least. I'll write about that, but I don't think there's enough to pin the outage on Manjaro like with the other outages.

Unless of course, there  is something you know that I don't :woozy_face:

**Comment by JiaZhangJiaZhangJiaZhangJiaZhang** [comment]
```
Unless of course, there is something you know that I don't 🥴
```

First is the claim quoted from https://wiki.manjaro.org/index.php/Manjaro_FAQ
> No. Manjaro is configured to use its own dedicated software repositories, although you can still access the community-maintained Arch User Repository (AUR) for additional software, if you wish.

But on why AUR is *seemingly* supported in the Manjaro pamac (contradiction), that's probably the Manjaro company motive to broaden the *seemingly* supported packages (false impression). I've seen Manjaro posts on users requiring packages from AUR because it's not supported by the Manjaro official repository, like printer driver with the most common.

This isn't to be taken too seriously, I'm only about 50% confident.

**Comment by EmeraldSnorlax** [comment]
i think so far this is sufficient. besides, this is getting a little off topic from the original thread.

**Comment by AaronTechnic** [comment]
nice
